version: "3.9"
name: ${CONTAINER_NAME}

services:
 

  # db:
  #   image: postgres:16
  #   container_name: ${DB_CONTAINER_NAME}
    
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USER}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_NAME}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5434:5432"

  redis:
    image: redis:7
    container_name: ${REDIS_CONTAINER_NAME}
    command: redis-server --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  postgres_data:
